import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import { Activity, ArrowRight, Blocks, BookOpen, BrainCircuit, ChevronDown, CircleHelp, Command, Database, Github, LayoutDashboard, Moon, PanelLeftClose, Settings2, Sparkles, UploadCloud } from 'lucide-react'
import { api, connectTelemetry } from './api'
import { Dashboard } from './Dashboard'
import type { Checkpoint, Telemetry } from './types'

const GraphEditor = lazy(() => import('./GraphEditor').then(module => ({ default: module.GraphEditor })))

type Page = 'dashboard' | 'editor' | 'checkpoints' | 'integration'
const initial: Telemetry = { type: 'telemetry', mode: 'demo', status: 'idle', ticks_per_second: 30, step: 0, episode: 1, episode_step: 0, elapsed_seconds: 0, metrics: { reward: 0, actor_loss: 0, critic_loss: 0, entropy: 0, spike_rate: 0 }, history: [], events: [{ time: '--:--:--', type: 'info', message: 'Connect the FastAPI server to explore live telemetry.' }], environment: { agent: [0, .25, 0], target: [2.45, .25, -1.65], velocity: [0, 0, 0], instant_reward: 0, bounds: [-4, 4] }, neurons: [16, 32, 32, 12].map((count, i) => ({ name: ['Encoder', 'LIF layer 1', 'LIF layer 2', 'Action head'][i], values: Array.from({ length: count }, (_, n) => .15 + .7 * Math.abs(Math.sin(n * 3.41))) })) }

function CheckpointPage() {
  const [items, setItems] = useState<Checkpoint[]>([])
  const [message, setMessage] = useState('')
  const input = useRef<HTMLInputElement>(null)
  const refresh = () => api.checkpoints().then(setItems).catch(e => setMessage(String(e)))
  useEffect(() => { void refresh() }, [])
  const upload = async (file: File) => { try { await api.uploadCheckpoint(file); await refresh(); setMessage(`${file.name} added to the checkpoint library`) } catch (error) { setMessage(String(error)) } }
  return <main className="page-body utility-page"><div className="page-intro"><div><div className="eyebrow">ASSETS <span className="breadcrumb-dot">/</span> CHECKPOINTS</div><h1>Checkpoint library</h1><p>Keep pretrained weights alongside the JSON graphs that reference them.</p></div><button className="primary-button" onClick={() => input.current?.click()}><UploadCloud size={16}/> Upload checkpoint</button></div><div className="utility-grid"><div className="panel asset-panel"><div className="panel-heading"><div><span className="eyebrow">AVAILABLE WEIGHTS</span><h3>Saved checkpoints</h3></div><span className="small-badge outline">{items.length} FILES</span></div>{items.length ? <div className="checkpoint-list">{items.map(item => <div key={item.id} className="checkpoint-item"><span className="checkpoint-icon"><Database size={19}/></span><div><strong>{item.id}</strong><small>{(item.size_bytes / 1024 / 1024).toFixed(2)} MB · referenced by pretrained nodes</small></div><span className="file-ext">{item.id.split('.').at(-1)?.toUpperCase()}</span></div>)}</div> : <div className="asset-empty"><Database size={36}/><strong>No checkpoints uploaded</strong><p>Upload a .pt, .pth, .ckpt or .safetensors file, then select it on a pretrained node.</p><button className="secondary-button" onClick={() => input.current?.click()}>Choose file</button></div>}</div><div className="panel asset-tip"><span className="eyebrow">HOW IT WORKS</span><h3>Architecture + weights</h3><p>Network topology, parameters, splits and training flags live in a portable JSON graph. Large pretrained weights stay in separate checkpoint files.</p><div className="asset-tip-step"><span>01</span><div><b>Upload weights</b><small>Add an existing checkpoint to the library.</small></div></div><div className="asset-tip-step"><span>02</span><div><b>Place a pretrained node</b><small>Choose its checkpoint and output width.</small></div></div><div className="asset-tip-step"><span>03</span><div><b>Choose training behavior</b><small>Freeze weights or propagate input gradients independently.</small></div></div></div></div>{message && <div className="toast-message">{message}</div>}<input hidden ref={input} type="file" accept=".pt,.pth,.ckpt,.safetensors" onChange={e => { const file = e.target.files?.[0]; if (file) void upload(file); e.target.value = '' }}/></main>
}

function IntegrationPage({ data, onMode }: { data: Telemetry; onMode: (mode: 'demo' | 'external') => void }) {
  return <main className="page-body utility-page"><div className="page-intro"><div><div className="eyebrow">WORKSPACE <span className="breadcrumb-dot">/</span> INTEGRATION</div><h1>Connect a trainer</h1><p>The UI is ready for an external continuous-control training process.</p></div><span className="demo-badge">API v0.1</span></div><div className="utility-grid"><div className="panel integration-panel"><span className="eyebrow">DATA SOURCE</span><h3>Telemetry mode</h3><p>Select the synthetic preview or receive snapshots from a separate trainer adapter.</p><div className="mode-choices"><button className={data.mode === 'demo' ? 'active' : ''} onClick={() => onMode('demo')}><Sparkles size={20}/><strong>Demo stream</strong><span>Explore the interface with generated values.</span></button><button className={data.mode === 'external' ? 'active' : ''} onClick={() => onMode('external')}><Activity size={20}/><strong>External trainer</strong><span>Accept snapshots through the FastAPI bridge.</span></button></div><div className="integration-code"><span>Telemetry endpoint</span><code>POST http://127.0.0.1:8000/api/bridge/telemetry</code></div><div className="integration-code"><span>Command polling</span><code>GET http://127.0.0.1:8000/api/bridge/commands?after=0</code></div></div><div className="panel asset-tip"><span className="eyebrow">PERFORMANCE</span><h3>Built for low overhead</h3><p>Publish compact snapshots around 5–10 times per second. The included Python bridge uses a single latest-wins slot, background network work, a payload cap, and short timeouts.</p><div className="asset-tip-step"><span>01</span><div><b>Sample scalars</b><small>Aggregate losses, returns and spike rates in small windows.</small></div></div><div className="asset-tip-step"><span>02</span><div><b>Observe selectively</b><small>Sample one environment and a subset of neurons.</small></div></div><div className="asset-tip-step"><span>03</span><div><b>Keep training independent</b><small>Apply queued controls at safe trainer boundaries.</small></div></div></div></div><div className="panel docs-strip"><BookOpen size={20}/><div><strong>Integration guide</strong><span>See docs/INTEGRATION.md for the full snapshot schema and reference-framework mapping.</span></div><ArrowRight size={18}/></div></main>
}

export default function App() {
  const [page, setPage] = useState<Page>('dashboard')
  const [data, setData] = useState<Telemetry>(initial)
  const [online, setOnline] = useState(false)
  const [compact, setCompact] = useState(false)
  const [toast, setToast] = useState('')
  const speedTimer = useRef<number | undefined>(undefined)
  useEffect(() => connectTelemetry(setData, setOnline), [])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer) }, [toast])
  const command = async (action: string) => { try { setData(await api.control(action)) } catch (error) { setToast(`Control failed: ${String(error)}`) } }
  const speed = (value: number) => { setData(d => ({ ...d, ticks_per_second: value })); clearTimeout(speedTimer.current); speedTimer.current = window.setTimeout(async () => { try { setData(await api.speed(value)) } catch (error) { setToast(`Speed update failed: ${String(error)}`) } }, 180) }
  const mode = async (value: 'demo' | 'external') => { try { const response = await fetch('/api/bridge/mode', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mode: value }) }); if (!response.ok) throw new Error(response.statusText); setData(await response.json()) } catch (error) { setToast(`Mode change failed: ${String(error)}`) } }
  const navigate = (target: Page) => { setPage(target); window.scrollTo(0, 0) }
  return <div className={`app-shell ${compact ? 'compact' : ''}`}><aside className="sidebar"><div className="brand"><span className="brand-mark"><BrainCircuit size={24} strokeWidth={2.3}/></span><div><strong>spikeloom<span>.</span></strong><small>GUI</small></div></div><button className="workspace-switch" onClick={() => navigate('dashboard')}><span className="workspace-avatar">S</span><span><b>SNN Workspace</b><small>Personal project</small></span><ChevronDown size={15}/></button><nav className="main-nav"><span className="nav-heading">WORKSPACE</span><button className={page === 'dashboard' ? 'active' : ''} onClick={() => navigate('dashboard')}><LayoutDashboard size={18}/><span>Dashboard</span></button><button className={page === 'editor' ? 'active' : ''} onClick={() => navigate('editor')}><Blocks size={18}/><span>Network editor</span><span className="nav-new">NEW</span></button><span className="nav-heading nav-section">RESOURCES</span><button className={page === 'checkpoints' ? 'active' : ''} onClick={() => navigate('checkpoints')}><Database size={18}/><span>Checkpoints</span></button><button className={page === 'integration' ? 'active' : ''} onClick={() => navigate('integration')}><Settings2 size={18}/><span>Integration</span></button></nav><div className="sidebar-bottom"><div className="help-card"><span className="help-icon"><CircleHelp size={19}/></span><strong>Build something new</strong><p>Design a network with spiking layers and reusable modules.</p><button onClick={() => navigate('editor')}>Open editor <ArrowRight size={15}/></button></div><button className="collapse-button" onClick={() => setCompact(!compact)}><PanelLeftClose size={17}/><span>{compact ? 'Expand sidebar' : 'Collapse sidebar'}</span></button></div></aside><div className="app-main"><header className="topbar"><div className="topbar-path"><span>Workspace</span><span className="topbar-slash">/</span><b>{page === 'dashboard' ? 'Dashboard' : page === 'editor' ? 'Network editor' : page === 'checkpoints' ? 'Checkpoints' : 'Integration'}</b></div><div className="topbar-right"><span className="topbar-api"><span className={`connection-dot ${online ? '' : 'offline'}`}/>{online ? 'API online' : 'API offline'}</span><span className="topbar-divider"/><Moon size={18}/><span className="topbar-divider"/><span className="user-avatar">TB</span></div></header>{page === 'dashboard' ? <Dashboard data={data} online={online} onCommand={command} onSpeed={speed}/> : page === 'editor' ? <Suspense fallback={<main className="page-body">Loading network editor…</main>}><GraphEditor/></Suspense> : page === 'checkpoints' ? <CheckpointPage/> : <IntegrationPage data={data} onMode={mode}/>}<footer className="app-footer"><span>Spikeloom GUI <span className="muted">·</span> Training UI prototype</span><span>Designed for continuous control RL</span></footer></div>{toast && <div className="global-toast">{toast}<button onClick={() => setToast('')}>×</button></div>}</div>
}
